import type { BossType } from './types'

export interface LessonOption {
  k: string
  label: string
  correct: boolean
}

export interface LessonCard {
  id: string
  categoryId: string
  word: string
  prompt: string
  options: LessonOption[]
  meaningJa: string
  core: string
  exampleEn: string
  exampleJa: string
  bossHint: string
  bossWhere: string
  nuance?: string
  nextWord?: string
  nextTeaser?: string
}

export interface LessonCategory {
  id: string
  bossType: BossType
  title: string
  words: string
  level: number
  cards: LessonCard[]
}

export const LESSON_CATEGORIES: LessonCategory[] = [
  {
    id: 'but',
    bossType: 'short_text',
    title: 'でも・しかし系の言葉',
    words: 'However, Yet, Although, Nevertheless',
    level: 1,
    cards: [
      {
        id: 'but-1',
        categoryId: 'but',
        word: 'However',
        prompt: 'この後に続く文は、前の文と比べてどんな内容？',
        options: [
          { k: 'A', label: '同じ方向のこと（だから〜）', correct: false },
          { k: 'B', label: '反対のこと（でも〜）', correct: true },
          { k: 'C', label: 'まったく別の話題', correct: false },
        ],
        meaningJa: 'でも・しかし・それでも',
        core: '前の文と逆のことが続くサイン。',
        exampleEn: '"It was raining. However, they went outside."',
        exampleJa: '「雨が降っていた。それでも、彼らは外に出た。」',
        bossHint: 'お知らせ文で however が出たら、前の文と逆の情報が来ます。',
        bossWhere: '第1問に出やすい',
        nextWord: 'Yet',
        nextTeaser: 'However と似ているようで、少し違う。',
      },
      {
        id: 'but-2',
        categoryId: 'but',
        word: 'Yet',
        prompt: 'この後に続く文は、前の文と比べてどんな内容？',
        options: [
          { k: 'A', label: '反対のこと（でも〜）', correct: true },
          { k: 'B', label: '同じ方向のこと（だから〜）', correct: false },
          { k: 'C', label: '追加の情報（さらに〜）', correct: false },
        ],
        meaningJa: 'それでも・しかし',
        core: 'however と同じく逆接。ただし「予想に反して」というニュアンスが強い。',
        exampleEn: '"She was tired. Yet, she kept working."',
        exampleJa: '「彼女は疲れていた。それでも働き続けた。」',
        bossHint: 'yet は文頭に来ることが多く、予想外の展開を示すサイン。',
        bossWhere: '第1問に出やすい',
        nextWord: 'Although',
        nextTeaser: '文の途中で逆接をつなぐ言葉。',
      },
      {
        id: 'but-3',
        categoryId: 'but',
        word: 'Although',
        prompt: '"Although it was cold, ___" — 空欄にくる内容は？',
        options: [
          { k: 'A', label: '寒さについての追加説明', correct: false },
          { k: 'B', label: '寒さと逆のこと（外に出た、など）', correct: true },
          { k: 'C', label: '寒さの原因', correct: false },
        ],
        meaningJa: '〜だけれども・〜にもかかわらず',
        core: '文の中で逆接をつなぐ。although 節の後に、予想と逆の内容が来る。',
        exampleEn: '"Although it was cold, they went for a walk."',
        exampleJa: '「寒かったけれど、彼らは散歩に出かけた。」',
        bossHint: 'although は文頭に来ることが多い。後半に「意外な行動」が来たら根拠になる。',
        bossWhere: '第1問・第3問に出やすい',
      },
    ],
  },
  {
    id: 'so',
    bossType: 'short_text',
    title: 'だから・なので系の言葉',
    words: 'Therefore, Thus, As a result, Hence',
    level: 1,
    cards: [
      {
        id: 'so-1',
        categoryId: 'so',
        word: 'Therefore',
        prompt: 'この後に続く文は、前の文と比べてどんな関係？',
        options: [
          { k: 'A', label: '前の文の結果・結論', correct: true },
          { k: 'B', label: '前の文と逆のこと', correct: false },
          { k: 'C', label: '前の文に関係ない話', correct: false },
        ],
        meaningJa: 'だから・それゆえ・したがって',
        core: '前の文が「理由」、therefore の後が「結論・結果」。',
        exampleEn: '"She studied hard. Therefore, she passed the exam."',
        exampleJa: '「彼女は懸命に勉強した。だから、試験に合格した。」',
        bossHint: 'therefore の後が設問の正解根拠になることが多い。',
        bossWhere: '第1問・第6問に出やすい',
      },
    ],
  },
  {
    id: 'feel',
    bossType: 'long_story',
    title: '気持ちを表す言葉',
    words: 'disappointed, relieved, frustrated, eager',
    level: 1,
    cards: [
      {
        id: 'feel-1',
        categoryId: 'feel',
        word: 'relieved',
        prompt: 'この人の気持ちに近いのはどれ？',
        options: [
          { k: 'A', label: 'ほっとした・安心した', correct: true },
          { k: 'B', label: 'がっかりした・失望した', correct: false },
          { k: 'C', label: 'いらいらした・もどかしい', correct: false },
        ],
        meaningJa: 'ほっとした・安心した',
        core: '心配していたことが解消されたときの「ほっとした」感覚。',
        exampleEn: '"She was relieved to hear the good news."',
        exampleJa: '「彼女はその良いニュースを聞いてほっとした。」',
        bossHint: '第7問（長い物語）では登場人物の感情変化が設問になる。relieved はネガティブ→ポジティブの転換点。',
        bossWhere: '第7問に出やすい',
      },
    ],
  },
  {
    id: 'compare',
    bossType: 'essay_synthesis',
    title: 'どちらが〜かを表す言葉',
    words: 'rather than, as ... as, unlike, compared',
    level: 1,
    cards: [
      {
        id: 'compare-1',
        categoryId: 'compare',
        word: 'rather than',
        prompt: '"She chose reading rather than watching TV" — この文の意味は？',
        options: [
          { k: 'A', label: 'テレビを見る代わりに本を読んだ', correct: true },
          { k: 'B', label: 'テレビを見ながら本も読んだ', correct: false },
          { k: 'C', label: '本を読むよりテレビが好き', correct: false },
        ],
        meaningJa: '〜よりもむしろ・〜の代わりに',
        core: '2つの選択肢を比べて、前者を選んだことを示す。',
        exampleEn: '"She chose reading rather than watching TV."',
        exampleJa: '「彼女はテレビを見る代わりに読書を選んだ。」',
        bossHint: '第8問（意見論述）でよく出る比較表現。筆者の主張がどちら寄りかを読み取るヒント。',
        bossWhere: '第8問に出やすい',
      },
    ],
  },
  {
    id: 'intent',
    bossType: 'survey_blog',
    title: '文書が何を伝えたいか',
    words: 'claim, suggest, argue, imply, conclude',
    level: 1,
    cards: [
      {
        id: 'intent-1',
        categoryId: 'intent',
        word: 'suggest',
        prompt: '"The data suggests that..." — 筆者はどのくらい確信を持って言っている？',
        options: [
          { k: 'A', label: '「〜かもしれない」くらいの弱い主張', correct: true },
          { k: 'B', label: '「絶対に〜だ」という強い断言', correct: false },
          { k: 'C', label: '誰かの意見を引用している', correct: false },
        ],
        meaningJa: '〜を示唆する・〜かもしれないと示す',
        core: 'suggest は断定ではなく「〜の可能性を示す」弱い表現。',
        exampleEn: '"The data suggests that exercise improves mood."',
        exampleJa: '「データは運動が気分を改善することを示唆している。」',
        bossHint: '第2問（調査・ブログ）では筆者の主張の強さを問う設問が出やすい。suggest ≠ prove（証明）。',
        bossWhere: '第2問に出やすい',
      },
    ],
  },
  // ── Level 2 ──────────────────────────────────────
  {
    id: 'time',
    bossType: 'long_story',
    title: '時の流れを表す言葉',
    words: 'initially, eventually, meanwhile, previously',
    level: 2,
    cards: [
      {
        id: 'time-1',
        categoryId: 'time',
        word: 'initially',
        prompt: '「initially nervous」— この人はいつ緊張していた？',
        options: [
          { k: 'A', label: '最初のうちだけ', correct: true },
          { k: 'B', label: 'ずっと・最後まで', correct: false },
          { k: 'C', label: '突然', correct: false },
        ],
        meaningJa: '最初は・はじめのうちは',
        core: '後で状況が変わることを暗示する。eventually とセットで登場することが多い。',
        exampleEn: '"She was initially nervous, but soon relaxed."',
        exampleJa: '「彼女は最初は緊張していたが、すぐにリラックスした。」',
        bossHint: '登場人物の心境変化を追うとき重要。「最初→後で」の流れを見抜くポイント。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'eventually',
        nextTeaser: '「最初」の反対。時間の末に起きたことを示す言葉。',
      },
      {
        id: 'time-2',
        categoryId: 'time',
        word: 'eventually',
        prompt: '「he eventually became a professional」— プロになったのはいつ？',
        options: [
          { k: 'A', label: 'すぐに', correct: false },
          { k: 'B', label: '時間をかけた末に', correct: true },
          { k: 'C', label: '偶然に', correct: false },
        ],
        meaningJa: 'やがて・結局・最終的に',
        core: '時間や努力の積み重ねの末に起きたことを表す。物語の結末に向かう流れを示す。',
        exampleEn: '"After years of practice, he eventually became a professional."',
        exampleJa: '「何年もの練習の末、彼はやがてプロになった。」',
        bossHint: 'initially と対になることが多い。物語の展開を時系列で整理するときの目印。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'meanwhile',
        nextTeaser: '2つの出来事が同時進行するときに使う言葉。',
      },
      {
        id: 'time-3',
        categoryId: 'time',
        word: 'meanwhile',
        prompt: '「She studied. Meanwhile, her brother watched TV.」— 2人の行動の関係は？',
        options: [
          { k: 'A', label: '同時に別々のことをしていた', correct: true },
          { k: 'B', label: '同じことをしていた', correct: false },
          { k: 'C', label: '順番に同じことをした', correct: false },
        ],
        meaningJa: 'その一方で・その間に',
        core: '2つの出来事が同時進行していることを示す。複数の登場人物の行動を追うとき重要。',
        exampleEn: '"She studied for the exam. Meanwhile, her brother watched TV."',
        exampleJa: '「彼女は試験勉強をしていた。その一方で、弟はテレビを見ていた。」',
        bossHint: '「誰が何をしていたか」を整理する問題で登場する。並行する出来事の合図。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'previously',
        nextTeaser: '現在ではなく「以前の状態」を示す言葉。',
      },
      {
        id: 'time-4',
        categoryId: 'time',
        word: 'previously',
        prompt: '「The building was previously used as a school.」— この建物は今どうなっている？',
        options: [
          { k: 'A', label: '今も学校として使われている', correct: false },
          { k: 'B', label: '今は別の用途で使われている', correct: true },
          { k: 'C', label: '取り壊された', correct: false },
        ],
        meaningJa: '以前は・かつては・その前は',
        core: '現在の状況と過去の状況を比べるときに登場する。時系列を整理するヒントになる。',
        exampleEn: '"The building was previously used as a school."',
        exampleJa: '「その建物は以前、学校として使われていた。」',
        bossHint: '「現在の状況 vs 過去の状況」を比べる問題でよく登場する。',
        bossWhere: '第2問・第6問に出やすい',
      },
    ],
  },
  {
    id: 'degree',
    bossType: 'essay_synthesis',
    title: '程度・変化を表す言葉',
    words: 'significantly, gradually, barely, dramatically',
    level: 2,
    cards: [
      {
        id: 'degree-1',
        categoryId: 'degree',
        word: 'significantly',
        prompt: '「significantly increased」— 増加の程度は？',
        options: [
          { k: 'A', label: 'わずかに増えた', correct: false },
          { k: 'B', label: '大幅に増えた', correct: true },
          { k: 'C', label: '少しずつ増えた', correct: false },
        ],
        meaningJa: '大幅に・著しく・かなり',
        core: '変化や差が「大きい」ことを強調する。数値や状況の変化を説明する文でよく使われる。',
        exampleEn: '"The number of visitors significantly increased last year."',
        exampleJa: '「昨年、訪問者数が大幅に増加した。」',
        bossHint: 'グラフや統計の変化を読み取る問題でよく登場する。「大きな変化」を示す目印。',
        bossWhere: '第2問・第4問に出やすい',
        nuance: '形容詞 significant は「重要な・意義深い」の意味もある（例：a significant finding＝重要な発見）。副詞 significantly は「かなり」と「重要な意味で」の両方のニュアンスを持つ。',
        nextWord: 'gradually',
        nextTeaser: 'significantly とは逆に、ゆっくりした変化を表す言葉。',
      },
      {
        id: 'degree-2',
        categoryId: 'degree',
        word: 'gradually',
        prompt: '「gradually became more confident」— 自信はどのようについた？',
        options: [
          { k: 'A', label: '突然', correct: false },
          { k: 'B', label: '少しずつ', correct: true },
          { k: 'C', label: '完全に', correct: false },
        ],
        meaningJa: '少しずつ・徐々に・ゆっくりと',
        core: '急激ではなく、時間をかけてゆっくり変化することを表す。',
        exampleEn: '"She gradually became more confident in speaking English."',
        exampleJa: '「彼女は少しずつ英語を話すことに自信を持てるようになった。」',
        bossHint: '変化が「突然」か「徐々に」かを見分けることが解答の鍵になることがある。',
        bossWhere: '第6問・第7問に出やすい',
        nextWord: 'barely',
        nextTeaser: '「ギリギリ」「ほとんど〜ない」という限界を表す言葉。',
      },
      {
        id: 'degree-3',
        categoryId: 'degree',
        word: 'barely',
        prompt: '「I could barely keep my eyes open.」— この人の状態は？',
        options: [
          { k: 'A', label: '十分目を開けていられた', correct: false },
          { k: 'B', label: 'かろうじて・ほとんど目を開けられなかった', correct: true },
          { k: 'C', label: 'まったく目を開けられなかった', correct: false },
        ],
        meaningJa: 'かろうじて・ほとんど〜ない',
        core: 'ギリギリできる、またはほぼできない状況を表す。否定的なニュアンスが強い。',
        exampleEn: '"I was so tired that I could barely keep my eyes open."',
        exampleJa: '「私はとても疲れていて、目をほとんど開けていられなかった。」',
        bossHint: '登場人物の限界を描写するときに使われる。「ほぼ〜できない」と読むのがポイント。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'dramatically',
        nextTeaser: '「劇的」な変化を強調する言葉。significantly より感情的なニュアンス。',
      },
      {
        id: 'degree-4',
        categoryId: 'degree',
        word: 'dramatically',
        prompt: '「dramatically changed」— 変化の様子は？',
        options: [
          { k: 'A', label: '劇的で目を見張るほどの変化', correct: true },
          { k: 'B', label: '静かで小さな変化', correct: false },
          { k: 'C', label: '規則的な変化', correct: false },
        ],
        meaningJa: '劇的に・大きく・目を見張るほど',
        core: '変化が「ドラマチックに大きい」ことを強調する。significantly より感情的なニュアンスがある。',
        exampleEn: '"The internet has dramatically changed how we communicate."',
        exampleJa: '「インターネットは私たちのコミュニケーション方法を劇的に変えた。」',
        bossHint: '変化を描写する文で登場する。その変化がどのくらい大きいかを理解するのがポイント。',
        bossWhere: '第4問・第7問に出やすい',
      },
    ],
  },
  {
    id: 'add',
    bossType: 'survey_blog',
    title: '付け加え・強調の言葉',
    words: 'furthermore, in addition, indeed, overall',
    level: 2,
    cards: [
      {
        id: 'add-1',
        categoryId: 'add',
        word: 'furthermore',
        prompt: '「furthermore」が来たら、その文は前の文に何を加える？',
        options: [
          { k: 'A', label: '前の内容を否定する', correct: false },
          { k: 'B', label: '追加・補足の情報を加える', correct: true },
          { k: 'C', label: '結論を述べる', correct: false },
        ],
        meaningJa: 'さらに・その上・加えて',
        core: '前の内容に追加情報を加えるときに使う。moreover や in addition と同じ働き。',
        exampleEn: '"The product is affordable. Furthermore, it is easy to use."',
        exampleJa: '「その製品は手頃な価格だ。さらに、使いやすい。」',
        bossHint: '筆者が「メリット」や「理由」を列挙するときに使う目印。情報が続く合図。',
        bossWhere: '第2問・第4問に出やすい',
        nextWord: 'in addition',
        nextTeaser: '同じく「追加」を示す表現。チラシやお知らせで特によく登場する。',
      },
      {
        id: 'add-2',
        categoryId: 'add',
        word: 'in addition',
        prompt: '「In addition, transport is provided.」— この文の役割は？',
        options: [
          { k: 'A', label: '前の情報と対比する', correct: false },
          { k: 'B', label: '前の情報に新しい情報を追加する', correct: true },
          { k: 'C', label: '前の情報の原因を説明する', correct: false },
        ],
        meaningJa: '加えて・また・それに加えて',
        core: '前の文に続けて追加情報を導く表現。文頭に置いて使うことが多い。',
        exampleEn: '"The tour includes breakfast. In addition, transport is provided."',
        exampleJa: '「そのツアーには朝食が含まれている。加えて、交通手段も提供される。」',
        bossHint: 'お知らせやチラシで「特典」や「付帯サービス」を追加するときに使われる。',
        bossWhere: '第1問・第2問に出やすい',
        nextWord: 'indeed',
        nextTeaser: '「やっぱりそうだ」と前の内容を確認・強調する言葉。',
      },
      {
        id: 'add-3',
        categoryId: 'add',
        word: 'indeed',
        prompt: '「She said she was tired, and indeed she fell asleep.」— indeedの働きは？',
        options: [
          { k: 'A', label: '前の内容を否定する', correct: false },
          { k: 'B', label: '前の内容を強調・確認する', correct: true },
          { k: 'C', label: '前の内容と無関係なことを追加する', correct: false },
        ],
        meaningJa: '実際に・確かに・まさに',
        core: '前述の内容を強調・確認するときに使う。「やっぱりそうだ」というニュアンスを加える。',
        exampleEn: '"She said she was tired, and indeed she fell asleep immediately."',
        exampleJa: '「彼女は疲れていると言っていた。確かに、彼女はすぐに眠った。」',
        bossHint: '予想や説明が「正しかった」ことを確認する文脈で登場する。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'overall',
        nextTeaser: '全体をまとめる言葉。結論の近くに登場する。',
      },
      {
        id: 'add-4',
        categoryId: 'add',
        word: 'overall',
        prompt: '「Overall, the event was a success.」— この文は何を示す？',
        options: [
          { k: 'A', label: '新しいトピックの始まり', correct: false },
          { k: 'B', label: '全体的なまとめ・評価', correct: true },
          { k: 'C', label: '例外的な事例の紹介', correct: false },
        ],
        meaningJa: '全体的に・総合的に・全般的に',
        core: '細部ではなく全体を評価・まとめるときに使う。結論や要旨に近い文に多い。',
        exampleEn: '"Overall, the event was a great success."',
        exampleJa: '「全体的に、そのイベントは大成功だった。」',
        bossHint: '筆者の「まとめ・結論」を示す目印。この言葉が出たら文の要旨が近い。',
        bossWhere: '第4問・第8問に出やすい',
      },
    ],
  },
  {
    id: 'purpose',
    bossType: 'short_text',
    title: '文書の目的を読む動詞',
    words: 'announce, recommend, warn, describe',
    level: 2,
    cards: [
      {
        id: 'purpose-1',
        categoryId: 'purpose',
        word: 'announce',
        prompt: '「We are pleased to announce ...」— この文書の目的は？',
        options: [
          { k: 'A', label: '特定の行動を禁止する', correct: false },
          { k: 'B', label: '情報を広く伝える', correct: true },
          { k: 'C', label: '意見を議論する', correct: false },
        ],
        meaningJa: 'お知らせする・発表する',
        core: '公式な場で情報を広く伝える動詞。お知らせ文・チラシ・メールでよく使われる。',
        exampleEn: '"We are pleased to announce the opening of our new store."',
        exampleJa: '「新店舗のオープンをお知らせできることを嬉しく思います。」',
        bossHint: '「この文書の目的は何か」という問題で正解になることが多い動詞。',
        bossWhere: '第1問に出やすい',
        nextWord: 'recommend',
        nextTeaser: '読者に「〜した方がいい」と伝えるときの動詞。',
      },
      {
        id: 'purpose-2',
        categoryId: 'purpose',
        word: 'recommend',
        prompt: '「We recommend booking in advance.」— 筆者は何をしている？',
        options: [
          { k: 'A', label: '事前予約を禁止している', correct: false },
          { k: 'B', label: '事前予約を勧めている', correct: true },
          { k: 'C', label: '過去の予約状況を報告している', correct: false },
        ],
        meaningJa: '勧める・推薦する・おすすめする',
        core: '筆者が読者に「〜した方がいい」と伝えるときに使う。目的把握問題でよく問われる。',
        exampleEn: '"We recommend booking tickets in advance."',
        exampleJa: '「チケットは事前に予約することをお勧めします。」',
        bossHint: '「この文書が伝えたいことは何か」という問題で重要な動詞。',
        bossWhere: '第1問・第2問に出やすい',
        nuance: '動詞として使う場合、後ろには動名詞（〜ing）が来る。× recommend to do → ○ recommend doing。また「推薦状」は a letter of recommendation と名詞形になる。',
        nextWord: 'warn',
        nextTeaser: '危険や注意を伝える動詞。掲示や案内文でよく登場する。',
      },
      {
        id: 'purpose-3',
        categoryId: 'purpose',
        word: 'warn',
        prompt: '「The sign warns visitors not to touch the exhibits.」— この掲示の役割は？',
        options: [
          { k: 'A', label: '訪問者を案内する', correct: false },
          { k: 'B', label: '訪問者に注意を促す', correct: true },
          { k: 'C', label: '訪問者に感謝する', correct: false },
        ],
        meaningJa: '警告する・注意を促す',
        core: '危険やリスクについて読者に注意を呼びかける動詞。掲示・案内文の目的を問う問題で重要。',
        exampleEn: '"The sign warns visitors not to touch the exhibits."',
        exampleJa: '「その標識は見学者に展示物に触れないよう警告している。」',
        bossHint: '「この掲示の目的は何か」という問題で「注意を促すため」が正解になることが多い。',
        bossWhere: '第1問・第3問に出やすい',
        nextWord: 'describe',
        nextTeaser: '状況・様子・特徴を言葉で伝える動詞。長文で頻出。',
      },
      {
        id: 'purpose-4',
        categoryId: 'purpose',
        word: 'describe',
        prompt: '「The article describes life in a village.」— この記事は何をしている？',
        options: [
          { k: 'A', label: '村の生活を否定している', correct: false },
          { k: 'B', label: '村の生活を比較している', correct: false },
          { k: 'C', label: '村の生活を説明・描写している', correct: true },
        ],
        meaningJa: '描写する・説明する・述べる',
        core: '何かの特徴・様子・状況を言葉で伝える動詞。説明文・エッセイでよく使われる。',
        exampleEn: '"The article describes life in a small Japanese village."',
        exampleJa: '「その記事は日本の小さな村での生活を描写している。」',
        bossHint: '「筆者は何について話しているか」という問題で使われる。長文の主題把握に重要。',
        bossWhere: '第6問・第7問に出やすい',
      },
    ],
  },
  {
    id: 'attitude',
    bossType: 'long_story',
    title: '気持ち・態度の言葉（その2）',
    words: 'concerned, eager, skeptical, convinced',
    level: 2,
    cards: [
      {
        id: 'attitude-1',
        categoryId: 'attitude',
        word: 'concerned',
        prompt: '「She was concerned about her friend\'s health.」— 彼女の気持ちは？',
        options: [
          { k: 'A', label: '友人の健康を喜んでいる', correct: false },
          { k: 'B', label: '友人の健康を心配している', correct: true },
          { k: 'C', label: '友人の健康に満足している', correct: false },
        ],
        meaningJa: '心配している・懸念している',
        core: '問題や状況に対して不安を感じている状態。worried より少しフォーマルなニュアンス。',
        nuance: '「concerned with 〜」は「〜に関係している・〜を扱っている」の意味になる（例：This report is concerned with energy policy.＝このレポートはエネルギー政策を扱っている）。心配とはまったく別の使い方なので注意。',
        exampleEn: '"She was concerned about her friend\'s health."',
        exampleJa: '「彼女は友人の健康を心配していた。」',
        bossHint: '登場人物の感情を問う問題でよく登場する。「何を心配しているか」を文脈から読み取ることが重要。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'eager',
        nextTeaser: 'concerned とは逆のポジティブな意欲・期待を表す言葉。',
      },
      {
        id: 'attitude-2',
        categoryId: 'attitude',
        word: 'eager',
        prompt: '「The students were eager to learn.」— 生徒たちの状態は？',
        options: [
          { k: 'A', label: '学ぶことに疲れている', correct: false },
          { k: 'B', label: '学ぶことに意欲的', correct: true },
          { k: 'C', label: '学ぶことに不満を感じている', correct: false },
        ],
        meaningJa: '熱心な・意欲的な・〜したくてたまらない',
        core: '何かに対して強い意欲や期待を持っている状態。ポジティブな感情。',
        exampleEn: '"The students were eager to learn about the new topic."',
        exampleJa: '「生徒たちは新しいトピックについて学ぼうと意欲的だった。」',
        bossHint: '登場人物の動機を問う問題に登場する。「なぜ〜したのか」の答えのヒントになる。',
        bossWhere: '第5問・第6問に出やすい',
        nextWord: 'skeptical',
        nextTeaser: '疑問・不信感を持っている状態を表す言葉。対立する意見を読むときに重要。',
      },
      {
        id: 'attitude-3',
        categoryId: 'attitude',
        word: 'skeptical',
        prompt: '「Many scientists were skeptical about the theory.」— 科学者たちの態度は？',
        options: [
          { k: 'A', label: 'その理論を信じている', correct: false },
          { k: 'B', label: 'その理論に疑問を持っている', correct: true },
          { k: 'C', label: 'その理論に感謝している', correct: false },
        ],
        meaningJa: '懐疑的な・疑っている・信じていない',
        core: '何かに対して疑問や不信感を持っている状態。意見の対立を描く文で使われる。',
        exampleEn: '"Many scientists were skeptical about the new theory."',
        exampleJa: '「多くの科学者はその新しい理論に懐疑的だった。」',
        bossHint: '複数の意見を比較する問題で重要。「反対側の立場」を示す文脈で登場する。',
        bossWhere: '第8問に出やすい',
        nextWord: 'convinced',
        nextTeaser: 'skeptical とは逆に、強く信じている・確信している状態。',
      },
      {
        id: 'attitude-4',
        categoryId: 'attitude',
        word: 'convinced',
        prompt: '「He was convinced that hard work leads to success.」— 彼の状態は？',
        options: [
          { k: 'A', label: '努力について迷っている', correct: false },
          { k: 'B', label: '努力の成果を確信している', correct: true },
          { k: 'C', label: '努力に失望している', correct: false },
        ],
        meaningJa: '確信している・納得している',
        core: '十分な根拠を持って強く信じている状態。疑いのない信念を表す。',
        nuance: '動詞 convince は「説得する」の意味。She convinced me to try it.（彼女は私を説得して試させた）。convinced は「説得された結果、確信している状態」でもある。convince A of B（AにBを納得させる）の形も頻出。',
        exampleEn: '"He was convinced that hard work would lead to success."',
        exampleJa: '「彼は努力が成功につながると確信していた。」',
        bossHint: '筆者や登場人物が「なぜその意見を持つか」を問う問題でよく登場する。',
        bossWhere: '第8問に出やすい',
      },
    ],
  },
]

export function getLessonCategory(id: string): LessonCategory | undefined {
  return LESSON_CATEGORIES.find(c => c.id === id)
}

export function getLessonCard(categoryId: string, cardId: string): LessonCard | undefined {
  return getLessonCategory(categoryId)?.cards.find(c => c.id === cardId)
}

export const LESSON_TOTAL = LESSON_CATEGORIES.reduce((sum, c) => sum + c.cards.length, 0)
